// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200129104317_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(50);

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufacturerId = 1,
                            ManufacturerName = "Samsung"
                        },
                        new
                        {
                            ManufacturerId = 2,
                            ManufacturerName = "Apple"
                        },
                        new
                        {
                            ManufacturerId = 3,
                            ManufacturerName = "Huawei"
                        },
                        new
                        {
                            ManufacturerId = 4,
                            ManufacturerName = "Xiaomi"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.MobilePhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasMaxLength(500);

                    b.Property<int>("ManufacturerId");

                    b.Property<string>("Memory")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(50);

                    b.Property<int?>("Price");

                    b.Property<string>("Processor")
                        .HasMaxLength(50);

                    b.Property<string>("Resolution")
                        .HasMaxLength(50);

                    b.Property<decimal?>("ScreeenSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasMaxLength(50);

                    b.Property<string>("Video")
                        .HasMaxLength(500);

                    b.Property<int?>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("MobilePhones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://img.zoommer.ge/zoommer-images/thumbs/0110804_samsung-galaxy-a01-2gb-ram-16gb-lte-a015fd-black_550.png",
                            ManufacturerId = 1,
                            Memory = "16 GB",
                            Name = "Samsung Galaxy Edge",
                            OperatingSystem = "Android 10.0",
                            Price = 700,
                            Processor = "Octa-core",
                            Resolution = "720 x 1560 pixels",
                            ScreeenSize = 7m,
                            Size = "146.3 x 70.9 x 8.3 mm",
                            Video = "https://www.youtube.com/watch?v=jZSDYEz6DYU",
                            Weight = 120
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://img.zoommer.ge/zoommer-images/thumbs/0103604_huawei-p-smart-z-4gb-ram-64gb-lte-black_220.png",
                            ManufacturerId = 1,
                            Memory = "",
                            Name = "Samsung A",
                            OperatingSystem = "Android 10.0",
                            Price = 800,
                            Processor = "Octa-core",
                            Resolution = "720 x 1560 pixels",
                            ScreeenSize = 8m,
                            Size = "146.3 x 70.9 x 8.3 mm",
                            Video = "https://www.youtube.com/watch?v=pQ8G57O6Ecc",
                            Weight = 150
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://img.zoommer.ge/zoommer-images/thumbs/0107238_apple-iphone-11-pro-single-sim-256gb-grey_220.png",
                            ManufacturerId = 2,
                            Memory = "",
                            Name = "Iphone 11",
                            OperatingSystem = "Android 10.0",
                            Price = 500,
                            Processor = "Octa-core",
                            Resolution = "720 x 1560 pixels",
                            ScreeenSize = 6m,
                            Size = "146.3 x 70.9 x 8.3 mm",
                            Video = "https://www.youtube.com/watch?v=H4p6njjPV_o",
                            Weight = 200
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://img.zoommer.ge/zoommer-images/thumbs/0107688_xiaomi-redmi-note-8t-global-version-4gb-ram-64gb-lte-grey_220.png",
                            ManufacturerId = 2,
                            Memory = "",
                            Name = "Iphone X",
                            OperatingSystem = "Android 10.0",
                            Price = 900,
                            Processor = "Octa-core",
                            Resolution = "720 x 1560 pixels",
                            ScreeenSize = 5m,
                            Size = "146.3 x 70.9 x 8.3 mm",
                            Video = "https://www.youtube.com/watch?v=6wvxyehsvFI",
                            Weight = 180
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://img.zoommer.ge/zoommer-images/thumbs/0107222_oneplus-7t-pro-dual-sim-8gb-ram-256gb-lte-haze-blue_220.png",
                            ManufacturerId = 3,
                            Memory = "",
                            Name = "Huawei P9 lite",
                            OperatingSystem = "Android 10.0",
                            Price = 300,
                            Processor = "Octa-core",
                            Resolution = "720 x 1560 pixels",
                            ScreeenSize = 7m,
                            Size = "146.3 x 70.9 x 8.3 mm",
                            Video = "https://www.youtube.com/watch?v=NqMk7eJlnxE",
                            Weight = 170
                        });
                });

            modelBuilder.Entity("DataLayer.Models.MobilePhone", b =>
                {
                    b.HasOne("DataLayer.Models.Manufacturer", "Manufacturer")
                        .WithMany("MobilePhones")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
